### ISSUE TITLE
Validate Edit Page Data ( Unit Price)

### ISSUE THREAD

**Issue by shekhar627** [SudiptoSarker/costallocationapp-v3#10]
Unit Price Change When one personnel is assigned to the same department, no man-hours are generated in the same month. Whenever there is a unit price change, it should be entered in the man-hours for the month in which the personnel is not assigned to the same department.

**Comment by shekhar627** [comment]
detect duplicate rows (unit price).
user can not save duplicate rows, remarks won't be counted.

**Comment by shekhar627** [comment]
cannot be able to save if the departments are same and also same man month's are inputted.

**Comment by adnanjabait** [comment]
This task is tested on 19/7/2023 10:09 AM (BD time) and working OK.
