### ISSUE TITLE
Validate Edit Page Data (Role)

### ISSUE THREAD

**Issue by shekhar627** [SudiptoSarker/costallocationapp-v3#12]
Role Change If a role is added for one personnel member, he/she will not be assigned to the same role. The total man-hours will not exceed 1.0. (In this case, the unit cost is the same)

**Comment by shekhar627** [comment]
detect duplicate rows (role).
user can not save duplicate rows, remarks won't be counted.

**Comment by shekhar627** [comment]
cannot be able to save rows, if roles are not changed.

**Comment by shekhar627** [comment]
role is now consisted with (section, department, in-charge, role).

**Comment by adnanjabait** [comment]
This task is tested on 19/7/2023 10:09 AM (BD time) and working OK.
