### ISSUE TITLE
Validate Edit Page Data (Unit Price/ Both)

### ISSUE THREAD

**Issue by shekhar627** [SudiptoSarker/costallocationapp-v3#13]
Unit price and role change If both unit price and role are not changed, an error is generated when saving. In case of an error, display the error message dialog and return to the screen using the Back button. Highlight the background of the name cell of the personnel concerned in red. It is possible that the personnel may be assigned to other departments in the same month (since different departments may have different unit costs).

**Comment by shekhar627** [comment]
detect duplicate rows (unit price/role).
user can not save duplicate rows, remarks won't be counted.

**Comment by shekhar627** [comment]
1. cannot be able to save if role is not changed.
2. cannot be able to save if department and unit price are same with other rows.
3. cannot be able to save if same department and same man month inputted with similar to other rows.

**Comment by shekhar627** [comment]
role is now consisted with (section, department, in-charge, role).

**Comment by adnanjabait** [comment]
This task is tested on 19/7/2023 10:09 AM (BD time) and working OK.
