### ISSUE TITLE
Make selected column compulsory for each entry

### ISSUE THREAD

**Issue by shekhar627** [SudiptoSarker/costallocationapp-v3#14]
Make 4 columns required for any entry into the edit page (assignment table).
Columns :

1. section
2. department
3. company
4. unit cost

**Comment by shekhar627** [comment]
development done, ready for testing.

**Comment by adnanjabait** [comment]
Now the 4 columns are required for each entries.
An alert message is showing for those required columns if any column entry is missing.

This task is tested on 18/7/2023 8:35 AM (BD time) and working OK.
