### ISSUE TITLE
Select multi row for approval

### ISSUE THREAD

**Issue by SudiptoSarker** [SudiptoSarker/costallocationapp-v3#15]

**Comment by SudiptoSarker** [comment]
Jexcel does not provide multi-row selection.

we can approve multi-row using customize ways.
#click on the row that is pending approval, you can click on multiple row 
#after clicking multiple row, now click on the approval button. the row you clicked for approval will be approved.
#back-end: we are storing the row that is pending approval and click for approval.
#validation: if you clicked a row that is not pending request, then that row will remain as it is.

**Comment by SudiptoSarker** [comment]
multiple rows selection and deselect are done. 
we can select multiple rows at a time and approve those selected rows.
before saving we can also deselect from approved rows.

**Comment by adnanjabait** [comment]
1. Multiple rows selection and deselect are working perfectly.
2. Selection color light yellow is showing perfectly
3. After deselecting a selected row the row is acting like its previous behavior.
4. Selected rows can approve perfectly and it is saved after hitting the save button.

This task is tested on 17/7/2023 9:03 AM (BD time) and working OK.
