### ISSUE TITLE
Validate actual cost menu's fields

### ISSUE THREAD

**Issue by adnanjabait** [SudiptoSarker/costallocationapp-v3#16]
Make the employee information fields disable for the actual cost menu.

![Image](https://user-images.githubusercontent.com/132339523/252906322-cdf7e1db-5856-475d-bc22-a3472d9a747c.png)

**Comment by SudiptoSarker** [comment]
all the fields in the actual cost page are disabled.

**Comment by adnanjabait** [comment]
This task is tested on 17/7/2023 2:16 PM (BD time) and showing OK.
