### ISSUE TITLE
Validate actual cost confirmation page's fields

### ISSUE THREAD

**Issue by adnanjabait** [SudiptoSarker/costallocationapp-v3#17]
Make the employee information columns no editable in actual cost confirmation page.

![Image](https://user-images.githubusercontent.com/132339523/252908061-650e17ae-867c-4b5b-b97d-d846537dc900.png)

**Comment by SudiptoSarker** [comment]
On the cost confirmation page, only actual cost man month and actual cost is enabled and other columns are disabled.

**Comment by adnanjabait** [comment]
This task is tested on 17/7/2023 2:17 PM (BD time) and showing OK.
