### ISSUE TITLE
Remove unnecessary columns in actual cost confirm page

### ISSUE THREAD

**Issue by adnanjabait** [SudiptoSarker/costallocationapp-v3#18]
Remove the unnecessary columns those are now showing in the actual cost confirmation page.

![Image](https://user-images.githubusercontent.com/132339523/252909412-85eda508-7544-44e6-81e9-d8924e67e9fc.png)

**Comment by SudiptoSarker** [comment]
The extra column from the actual cost confirm page has been removed.
please check this on our server.

**Comment by adnanjabait** [comment]
This task is tested on 17/7/2023 2:17 PM (BD time) and showing OK.
