### ISSUE TITLE
Make non editable calculated forecasted cost in edit page

### ISSUE THREAD

**Issue by adnanjabait** [SudiptoSarker/costallocationapp-v3#27]
Make the forecasted column non editable in edit page. Right now in edit page the forecasted cost column showing the calculated cost for the respective months and it is editable which is not as per our requirements. 
So the forecasted cost column in edit page should be non editable as it is a calculated value.

![Image](https://user-images.githubusercontent.com/132339523/253491811-b0427c9b-3154-49b5-832d-3d93b737c61f.png)

**Comment by SudiptoSarker** [comment]
The forecasted cost is read-only now. 
Row and Cell color will not show for forecasted cost because this value is calculated based on the formula on unit price * man month.

**Comment by adnanjabait** [comment]
Now the columns are non editable which are showing calculated forecasted cost in edit page.

This task is tested on 17/7/2023 12:05 PM (BD time) and working OK.
