### ISSUE TITLE
Track the delete request in change history

### ISSUE THREAD

**Issue by adnanjabait** [SudiptoSarker/costallocationapp-v3#33]
Scenario:
1. Delete a row from the edit page
2. Delete request for the row should be tracked in the change history

Expected:
1. There should be a track for the deleted row request in change history.

**Comment by SudiptoSarker** [comment]
This task is done.
Note: this is a new task. We did not store the deleted history before. 

Scenario: 
1. single row delete history. (Done)
2. multiple rows delete the history. (Done)
3. add a new employee and delete another assignment row at the same operation. (Done)
4. add a new employee, update cells, and delete assignment, these three operation at the same time. (Done)
