### ISSUE TITLE
Make input enabled for the unapproved row

### ISSUE THREAD

**Issue by adnanjabait** [SudiptoSarker/costallocationapp-v3#4]
For unapproved row, there should be option to edit the cell or edit the whole row by editor.
**Present scenario:**
1. Delete a row and send a approve request.
2. If the approve request is denied the row shows red in the edit page
3. The red row cell can not be edited.
**Expected scenario:**
1. Delete a row and send a approve request.
2. If the approve request is denied the row shows red in the edit page
3. The red row cell should be editable.

Correction feedback:
1. When any unapproved deleted row's cell is updated the red color row will act as a normal row.
2. Make sure the delete request has a track in the change history.
3. The new cell update request will be sent to the approval page and in approval page the row will act as a normal row

**Comment by SudiptoSarker** [comment]
note from the developer:
       The task is completed.
       Unapproved/Pending Deleted Request is now editable. 
       If changes occur and are saved from deleted edit row. then that row will behave like normal row.

**Comment by adnanjabait** [comment]
This task is tested on 19/7/2023 10:09 AM (BD time) and working OK.
