### ISSUE TITLE
Select multiple cell for approve

### ISSUE THREAD

**Issue by adnanjabait** [SudiptoSarker/costallocationapp-v3#8]
select multiple cell and approve them

**Comment by SudiptoSarker** [comment]
we can approve multi-cell using customize ways.
#click on the cells that are pending approval, you can click on multiple cells
#after clicking multiple cells, now click on the approval button. the cells you clicked for approval will be approved.
#back-end: we are storing the cells that are pending approval and click for approval.
#validation: if we you clicked a cells that are not pending request, then that cell will remain as it is.

**Comment by SudiptoSarker** [comment]
multiple cell selection and deselect are done. 
we can select multiple cells at a time and approve those selected cells.
before saving we can also deselect from approved cells.

**Comment by adnanjabait** [comment]
1. Select and deselect multiple cells feature is working on server
2. Selected cell color is light yellow and showing perfectly.
3. After deselect a cell it acts like its previous behavior.
4. Undo a approve cell and save an approved cell is working perfectly.

This task is tested on 17/7/2023 9:09 AM (BD time) and working OK.
